#
# Copyright (c) Contributors to the Open 3D Engine Project. For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(ENABLED_GEMS
    GameState
    ImGui
    ScriptEvents
    ExpressionEvaluation
    Gestures
    CertificateManager
    DebugDraw
    SceneProcessing
    GraphCanvas
    Multiplayer
    Multiplayer_ScriptCanvas
    AudioSystem
    Camera
    EMotionFX
    PhysX5
    CameraFramework
    ScriptCanvas
    ScriptCanvasPhysics
    ScriptCanvasTesting
    PhysX5Debug
    WhiteBox
    FastNoise
    SurfaceData
    GradientSignal
    Vegetation
    GraphModel
    LandscapeCanvas
    NvCloth
    Maestro
    TextureAtlas
    LmbrCentral
    LyShine
    LyShineExamples
    Atom
    Presence
    LocalUser
    SaveData
    MultiplayerSample
    StartingPointInput
    EditorPythonBindings
    PrefabBuilder
    MaterialEditor
    UiBasics
    character_mps
    props_mps
    landscape_mps
    kb3d_mps
    level_art_mps
    pbr_material_pack_mps
    DiffuseProbeGrid
    Terrain
    Profiler
    Stars
)
