#
# Copyright (c) Contributors to the Open 3D Engine Project
# 
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/AutoGen/NetworkAnimationComponent.AutoComponent.xml
    Source/AutoGen/NetworkCharacterComponent.AutoComponent.xml
    Source/AutoGen/NetworkHitVolumesComponent.AutoComponent.xml
    Source/AutoGen/NetworkPlayerSpawnerComponent.AutoComponent.xml
    Source/AutoGen/NetworkRigidBodyComponent.AutoComponent.xml
    Source/AutoGen/NetworkTraceComponent.AutoComponent.xml
    Source/AutoGen/NetworkWeaponsComponent.AutoComponent.xml
    Source/AutoGen/SimplePlayerCameraComponent.AutoComponent.xml
    Source/AutoGen/WasdPlayerMovementComponent.AutoComponent.xml
    Source/Components/ExampleFilteredEntityComponent.h
    Source/Components/ExampleFilteredEntityComponent.cpp
    Source/Components/NetworkAnimationComponent.cpp
    Source/Components/NetworkAnimationComponent.h
    Source/Components/NetworkCharacterComponent.cpp
    Source/Components/NetworkCharacterComponent.h
    Source/Components/NetworkHitVolumesComponent.cpp
    Source/Components/NetworkHitVolumesComponent.h
    Source/Components/NetworkPlayerSpawnerComponent.cpp
    Source/Components/NetworkPlayerSpawnerComponent.h
    Source/Components/NetworkRigidBodyComponent.cpp
    Source/Components/NetworkRigidBodyComponent.h
    Source/Components/NetworkTraceComponent.cpp
    Source/Components/NetworkTraceComponent.h
    Source/Components/NetworkWeaponsComponent.cpp
    Source/Components/NetworkWeaponsComponent.h
    Source/Components/SimplePlayerCameraComponent.cpp
    Source/Components/SimplePlayerCameraComponent.h
    Source/Components/WasdPlayerMovementComponent.cpp
    Source/Components/WasdPlayerMovementComponent.h
    Source/Weapons/BaseWeapon.cpp
    Source/Weapons/BaseWeapon.h
    Source/Weapons/IWeapon.h
    Source/Weapons/ProjectileWeapon.cpp
    Source/Weapons/ProjectileWeapon.h
    Source/Weapons/TraceWeapon.cpp
    Source/Weapons/TraceWeapon.h
    Source/Weapons/WeaponGathers.cpp
    Source/Weapons/WeaponGathers.h
    Source/Weapons/WeaponTypes.cpp
    Source/Weapons/WeaponTypes.h
    Source/MultiplayerSampleSystemComponent.cpp
    Source/MultiplayerSampleSystemComponent.h
    Source/MultiplayerSampleTypes.h
)
